In [89]:
import numpy as np
import pandas as pd
from google.colab import files
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Sequential
from keras.layers import Dense

In [ ]:
uploaded = files.upload()

Saving modified_data.csv to modified_data.csv


In [ ]:
data = pd.read_csv('/content/modified_data.csv')
data.head(1)

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500

[1 rows x 77 columns]

In [ ]:
data.shape

(1460, 77)

In [ ]:
data.drop('Id', inplace=True, axis=1)

In [ ]:
data.head(1)

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500

[1 rows x 76 columns]

In [ ]:
original_features = list(data.columns)
len(original_features)

76

In [ ]:
features_valmiss = data.columns[data.isna().any()]

len(features_valmiss)

15

In [ ]:
bfill, mean_fill = [], []

In [ ]:
for feature in features_valmiss:
    print(feature,'', data[feature].isna().sum()/len(data)*100, '', data[feature].dtype)
    if data[feature].dtype == 'float64':
      mean_fill.append(feature)
    else:
        bfill.append(feature)

LotFrontage  17.73972602739726  float64
MasVnrType  0.547945205479452  object
MasVnrArea  0.547945205479452  float64
BsmtQual  2.5342465753424657  object
BsmtCond  2.5342465753424657  object
BsmtExposure  2.6027397260273974  object
BsmtFinType1  2.5342465753424657  object
BsmtFinType2  2.6027397260273974  object
Electrical  0.0684931506849315  object
FireplaceQu  47.26027397260274  object
GarageType  5.5479452054794525  object
GarageYrBlt  5.5479452054794525  float64
GarageFinish  5.5479452054794525  object
GarageQual  5.5479452054794525  object
GarageCond  5.5479452054794525  object


In [ ]:
bfill

['MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [ ]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [ ]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(), inplace = True)

In [ ]:
for feature in bfill:
  data[feature].fillna(method = 'bfill', inplace = True)

In [ ]:
data.columns[data.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [ ]:
data['FireplaceQu'].fillna(method = 'ffill', inplace = True)

Encodng the dataset: to make the categorical data be numeric

In [ ]:
cat_features = list(data.select_dtypes(include=['object']).columns)
cat_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
numerical = list(set(original_features) - set(cat_features))
numerical

['EnclosedPorch',
 'OpenPorchSF',
 'BsmtFullBath',
 'BsmtUnfSF',
 'ScreenPorch',
 'LotArea',
 'OverallCond',
 'MasVnrArea',
 'LotFrontage',
 'FullBath',
 '3SsnPorch',
 '1stFlrSF',
 'MiscVal',
 'YearRemodAdd',
 'HalfBath',
 'WoodDeckSF',
 'GarageYrBlt',
 'TotalBsmtSF',
 'KitchenAbvGr',
 'YrSold',
 'GarageCars',
 'PoolArea',
 'SalePrice',
 'YearBuilt',
 'BedroomAbvGr',
 'BsmtHalfBath',
 'MoSold',
 '2ndFlrSF',
 'OverallQual',
 'MSSubClass',
 'Fireplaces',
 'BsmtFinSF2',
 'TotRmsAbvGrd',
 'LowQualFinSF',
 'BsmtFinSF1',
 'GarageArea',
 'GrLivArea']

In [ ]:
nominal = ['MSZoning', 'LandContour', 'Neighborhood']
ordinal = list(set(cat_features) - set(nominal))

In [ ]:
target = ['SalePrice']

Nominals = One Hot Encoding, Categoricals = Categorical encoding, Ordinal = Integer Encoding, think of order

In [ ]:
df_nominal = pd.get_dummies(data[nominal])
df_nominal
#one hot encoding

MSZoning_C (all)  MSZoning_FV  ...  Neighborhood_Timber  Neighborhood_Veenker
0                    0            0  ...                    0                     0
1                    0            0  ...                    0                     1
2                    0            0  ...                    0                     0
3                    0            0  ...                    0                     0
4                    0            0  ...                    0                     0
...                ...          ...  ...                  ...                   ...
1455                 0            0  ...                    0                     0
1456                 0            0  ...                    0                     0
1457                 0            0  ...                    0                     0
1458                 0            0  ...                    0                     0
1459                 0            0  ...                    0                     0

[1460 rows x 34 columns]

In [ ]:
for feature in ordinal:
  data[feature] = data[feature].astype('category').cat.codes

df_ordinal = data[ordinal]
df_ordinal

BldgType  BsmtExposure  BsmtCond  ...  RoofMatl  Foundation  BsmtFinType1
0            0             3         3  ...         1           2             2
1            0             1         3  ...         1           1             0
2            0             2         3  ...         1           2             2
3            0             3         1  ...         1           0             0
4            0             0         3  ...         1           2             2
...        ...           ...       ...  ...       ...         ...           ...
1455         0             3         3  ...         1           2             5
1456         0             3         3  ...         1           1             0
1457         0             3         1  ...         1           4             2
1458         0             2         3  ...         1           1             2
1459         0             3         3  ...         1           1             1

[1460 rows x 36 columns]

In [ ]:
df_numerical = data[numerical]

In [ ]:
new_data = pd.concat([df_nominal, df_ordinal, df_numerical], axis=1)

In [ ]:
new_data.head(3)

MSZoning_C (all)  MSZoning_FV  ...  GarageArea  GrLivArea
0                 0            0  ...         548       1710
1                 0            0  ...         460       1262
2                 0            0  ...         608       1786

[3 rows x 107 columns]

In [ ]:
new_data.shape

(1460, 107)

Now we standardize the data (Normalization in this case)

In [ ]:
new_data.drop('SalePrice', axis = 1, inplace = True)

In [ ]:
x = new_data.to_numpy()
x

array([[   0.,    0.,    0., ...,  706.,  548., 1710.],
       [   0.,    0.,    0., ...,  978.,  460., 1262.],
       [   0.,    0.,    0., ...,  486.,  608., 1786.],
       ...,
       [   0.,    0.,    0., ...,  275.,  252., 2340.],
       [   0.,    0.,    0., ...,   49.,  240., 1078.],
       [   0.,    0.,    0., ...,  830.,  276., 1256.]])

In [92]:
x = StandardScaler().fit_transform(x)
x.shape

(1460, 106)

In [ ]:
y = data[target]

In [ ]:
y = data[target].to_numpy()

In [ ]:
y.shape

(1460, 1)

In [ ]:
y = StandardScaler().fit_transform(y)
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

Feature Extraction using PCA

In [ ]:
pca = PCA(n_components = 2)

In [ ]:
p_comp = pca.fit_transform(x) #2d approximation of 106 features in dataset. PCA 1 carries the most info decreasing to PCAn

In [ ]:
p_comp

array([[ 2.44330927, -1.27803232],
       [ 0.31646055,  2.63803787],
       [ 2.85722035, -0.81058869],
       ...,
       [ 1.26182562, -0.85922036],
       [-2.85096743,  3.29457726],
       [-0.77738617,  2.78997945]])

In [ ]:
pca.explained_variance_ratio_ #training on 14% of the dataset

array([0.10560233, 0.04472092])

In [ ]:
#pca_var = PCA(.8) all components that carry a % of info

In [ ]:
#newer_data = pca_var.fit_transform(x)

In [ ]:
#newer_data.shape

(1460, 52)

Creating a new dataset with y and the pca components

In [ ]:
df = pd.DataFrame(p_comp, columns = ['PCA 1', 'PCA 2'])
df['Target'] = y
df

PCA 1     PCA 2    Target
0     2.443309 -1.278032  0.347273
1     0.316461  2.638038  0.007288
2     2.857220 -0.810589  0.536154
3    -1.333155  0.426959 -0.515281
4     5.220985 -0.249833  0.869843
...        ...       ...       ...
1455  1.335075 -2.288566 -0.074560
1456  1.112796  3.257033  0.366161
1457  1.261826 -0.859220  1.077611
1458 -2.850967  3.294577 -0.488523
1459 -0.777386  2.789979 -0.420841

[1460 rows x 3 columns]

Train the model (LassoCV)

In [ ]:
reg = LassoCV()

In [ ]:
reg.fit(p_comp,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [ ]:
reg.coef_

array([0.25387739, 0.01887698])

Training with the Sequential model

In [86]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [112]:
xTrain.shape

(1168, 106)

In [113]:
yTrain.shape

(1168, 1)

In [111]:
xTest.shape

(292, 106)

In [114]:
yTest.shape

(292, 1)

In [156]:
model = keras.Sequential(
    [
        layers.Dense(64, activation="relu"),
        layers.Dense(64, activation="relu"),
        layers.Dense(1),
    ]
)

x1 = tf.ones((292, 106))
y1 = model(x1)

In [ ]:
model.summary()

In [161]:
model.compile(loss = 'mse', optimizer = 'rmsprop', metrics = ['mae', 'mse'])

In [162]:
history = model.fit(xTrain, yTrain, epochs = 500, validation_split = 0.2, verbose = 0)

In [164]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist

loss       mae       mse  val_loss   val_mae   val_mse  epoch
0    0.484146  0.448942  0.484146  0.165250  0.294823  0.165250      0
1    0.196210  0.286547  0.196210  0.147147  0.288888  0.147147      1
2    0.137032  0.234891  0.137032  0.123577  0.254522  0.123577      2
3    0.105090  0.202270  0.105090  0.113540  0.246874  0.113540      3
4    0.087097  0.178988  0.087097  0.119340  0.253672  0.119340      4
..        ...       ...       ...       ...       ...       ...    ...
495  0.001207  0.024107  0.001207  0.099409  0.202416  0.099409    495
496  0.001802  0.027695  0.001802  0.100511  0.203044  0.100511    496
497  0.001224  0.023565  0.001224  0.096922  0.201695  0.096922    497
498  0.002237  0.028619  0.002237  0.096011  0.201402  0.096011    498
499  0.001181  0.022763  0.001181  0.105479  0.205204  0.105479    499

[500 rows x 7 columns]